### ISSUE TITLE
Help text

### ISSUE THREAD

**Issue by inafact** [h4us/p-code-playground#6]
PgUp / PgDn →Arrow Up / Arrow Down ?

**Comment by inafact** [comment]
It recalls local history, back & forward. → Recall local history, back & forward.
It recalls server history, back & forward. → Recall server history, back & forward.
P-Code[s] are running on 8 individual buses. → P-Code playground has 8 individual buses.

**Comment by seiko-mikami-project** [comment]
P-Code's language specification → P-Code language specification

**Comment by hemokosa** [comment]
すみません、違うアカウントからコメント入れてしまいました:-P

**Comment by hysysk** [comment]
Local commandsの下に皆には送られませんよ、というのが一言あるといいのかな。
These commands are not sent to the public timeline. とか？

- w/ opening history pane,  はなくてもいいかなと思いました。
- Prefix is '$ ' → The prefix is '$ '
- Set target audio → Set the target audio
- You can choose which one to use for evaluating your code → You can choose it to run your code
- Default value is 'auto' → The default is 'auto'
